### ISSUE TITLE
별도 값에 따른 Background-image display

### ISSUE THREAD

**Issue by webhacking** [wixsoft/Bodleian#6]
랜덤으로 클래스를 추가해서, 백그라운드 이미지를 보여주고있는데 이 상태에서 서버나,클라이언트 둘중한곳에서 전에 추가된 클래스를 저장해서 다음에 요청했을때 중복된 이미지를 보여주지않음으로써 이용자 이용감 개선하고싶은데 어떰. 어떤 방식이 좋은 방식일까

```javascript
setTimeout(function(){
      $('._bg_mask>div').addClass(Wixsoft.Banner.Images[Math.floor(Math.random() * 4)])
    },500);
```

```css
._banner ._bg_mask>div.one {background: url("/assets/images/background/re-min.jpg") 50% -50px no-repeat}
._banner ._bg_mask>div.two {background: url("/assets/images/background/awesome-japan-wallpaper-4372-4603-hd-wallpapers-min.jpg") 50% -50px no-repeat}
._banner ._bg_mask>div.three {background: url("/assets/images/background/photo copy-min.JPG") 50% -50px no-repeat}
._banner ._bg_mask>div.four {background: url("/assets/images/background/t-min.jpg") 50% -50px no-repeat}

```
